import { BookmarkTreeNode } from "../types/BookmarkTreeNode";
import { BookmarksApi } from "../services/BookmarksApi";
import { SyncBookmarksAdapter } from "../services/SyncBokmarksAdapter";

const bookmarksInitialState: BookmarkTreeNode[] = [
  {
    id: "menu________",
    title: "Bookmarks Menu",
    index: 0,
    dateAdded: 1677328173656,
    type: "folder",
    parentId: "root________",
    dateGroupModified: 1503756599000,
    children: [
      {
        id: "1jVjScsEvZPT",
        title: "Recent Tags",
        index: 0,
        dateAdded: 1503756599000,
        type: "bookmark",
        url: "place:type=6&sort=14&maxResults=10",
        parentId: "menu________",
      },
    ],
  },
  {
    id: "toolbar_____",
    title: "Bookmarks Toolbar",
    index: 1,
    dateAdded: 1677328173656,
    type: "folder",
    parentId: "root________",
    dateGroupModified: 1677328173716,
    children: [
      {
        id: "n6zhBRRJJCEH",
        title: "Most Visited",
        index: 0,
        dateAdded: 1503756599000,
        type: "bookmark",
        url: "place:sort=8&maxResults=10",
        parentId: "toolbar_____",
      },
      {
        id: "TYXd4jSAfexW",
        title: "Fedora Docs",
        index: 1,
        dateAdded: 1158286602000,
        type: "bookmark",
        url: "https://docs.fedoraproject.org/",
        parentId: "toolbar_____",
      },
      {
        id: "stI4klAQBVJe",
        title: "Fedora Magazine",
        index: 2,
        dateAdded: 1367341224000,
        type: "bookmark",
        url: "https://fedoramagazine.org/",
        parentId: "toolbar_____",
      },
      {
        id: "QD2eNoSdS-m0",
        title: "Fedora Project",
        index: 3,
        dateAdded: 1130967903000,
        type: "folder",
        parentId: "toolbar_____",
        dateGroupModified: 1619190522000,
        children: [
          {
            id: "A0WWXRpR0jAq",
            title: "Get Fedora",
            index: 0,
            dateAdded: 1503757590000,
            type: "bookmark",
            url: "https://getfedora.org/",
            parentId: "QD2eNoSdS-m0",
          },
          {
            id: "oe6d3wxaIOQM",
            title: "More Downloads",
            index: 1,
            dateAdded: 1503757608000,
            type: "folder",
            parentId: "QD2eNoSdS-m0",
            dateGroupModified: 1503757721000,
            children: [
              {
                id: "qyoqXNd6I-e0",
                title: "Fedora Spins (Desktop Environments)",
                index: 0,
                dateAdded: 1503757672000,
                type: "bookmark",
                url: "https://spins.fedoraproject.org/",
                parentId: "oe6d3wxaIOQM",
              },
              {
                id: "feVp2Rsd8FSb",
                title: "Fedora Labs (Functional Bundles)",
                index: 1,
                dateAdded: 1503757699000,
                type: "bookmark",
                url: "https://labs.fedoraproject.org/",
                parentId: "oe6d3wxaIOQM",
              },
              {
                id: "-OfA01w_yfVC",
                title: "Fedora ARM (IoT and More!)",
                index: 2,
                dateAdded: 1503757721000,
                type: "bookmark",
                url: "https://arm.fedoraproject.org/",
                parentId: "oe6d3wxaIOQM",
              },
              {
                id: "mcmhWZxeqTha",
                title: "Fedora Alternative Downloads",
                index: 3,
                dateAdded: 1503757712000,
                type: "bookmark",
                url: "https://alt.fedoraproject.org/",
                parentId: "oe6d3wxaIOQM",
              },
            ],
          },
          {
            id: "5cSruH85vA-d",
            title: "About the Fedora Project",
            index: 2,
            dateAdded: 1619190522000,
            type: "bookmark",
            url: "https://docs.fedoraproject.org/en-US/project/",
            parentId: "QD2eNoSdS-m0",
          },
          {
            id: "y-DxdjB3qg2G",
            title: "Ask Fedora (Community Support)",
            index: 3,
            dateAdded: 1351508148000,
            type: "bookmark",
            url: "https://ask.fedoraproject.org/",
            parentId: "QD2eNoSdS-m0",
          },
          {
            id: "Ng73QbrOhBlw",
            title: "Fedora Discussion",
            index: 4,
            dateAdded: 1544490673000,
            type: "bookmark",
            url: "https://discussion.fedoraproject.org/",
            parentId: "QD2eNoSdS-m0",
          },
          {
            id: "Uo7vDfHL_p2n",
            title: "Planet Fedora",
            index: 5,
            dateAdded: 1176675201000,
            type: "bookmark",
            url: "http://fedoraplanet.org/",
            parentId: "QD2eNoSdS-m0",
          },
          {
            id: "CqcQWhg4X3dj",
            title: "Fedora Community Blog",
            index: 6,
            dateAdded: 1463690518000,
            type: "bookmark",
            url: "https://communityblog.fedoraproject.org/",
            parentId: "QD2eNoSdS-m0",
          },
          {
            id: "9Y-Y3IzA-Ee1",
            title: "Get involved with the Fedora Project",
            index: 7,
            dateAdded: 1241209418000,
            type: "bookmark",
            url: "https://whatcanidoforfedora.org/",
            parentId: "QD2eNoSdS-m0",
          },
        ],
      },
      {
        id: "bu8fdOZAucTS",
        title: "User Communities",
        index: 4,
        dateAdded: 1503756648000,
        type: "folder",
        parentId: "toolbar_____",
        dateGroupModified: 1503757541000,
        children: [
          {
            id: "krHWsIX7Y8XP",
            title: "Fedora Forum",
            index: 0,
            dateAdded: 1130967896000,
            type: "bookmark",
            url: "https://forums.fedoraforum.org/",
            parentId: "bu8fdOZAucTS",
          },
          {
            id: "4YJk5V_Eq7eY",
            title: "r/Fedora on Reddit",
            index: 1,
            dateAdded: 1503756962000,
            type: "bookmark",
            url: "https://www.reddit.com/r/Fedora/",
            parentId: "bu8fdOZAucTS",
          },
          {
            id: "BQe7iB4RtXde",
            title: "Fedora on Facebook",
            index: 2,
            dateAdded: 1503757272000,
            type: "bookmark",
            url: "https://www.facebook.com/TheFedoraProject",
            parentId: "bu8fdOZAucTS",
          },
          {
            id: "HsGXHXSSdCAX",
            title: "@fedora on Twitter",
            index: 3,
            dateAdded: 1503757302000,
            type: "bookmark",
            url: "https://twitter.com/fedora",
            parentId: "bu8fdOZAucTS",
          },
          {
            id: "6xq7Ep-R7Rc5",
            title: "Fedora Telegram",
            index: 4,
            dateAdded: 1503757425000,
            type: "bookmark",
            url: "https://telegram.me/fedoranews",
            parentId: "bu8fdOZAucTS",
          },
          {
            id: "q1D3ksy2ZyTM",
            title: "Fedora on Discord Chat",
            index: 5,
            dateAdded: 1503757455000,
            type: "bookmark",
            url: "https://discordapp.com/invite/fedora",
            parentId: "bu8fdOZAucTS",
          },
          {
            id: "91tVyeam5_Mn",
            title: "Fedora on Diaspora",
            index: 6,
            dateAdded: 1503757541000,
            type: "bookmark",
            url: "https://diasp.org/u/fedora",
            parentId: "bu8fdOZAucTS",
          },
          {
            id: "HseynvOzu5wk",
            title: "#fedora IRC via Riot",
            index: 7,
            dateAdded: 1503757522000,
            type: "bookmark",
            url: "https://riot.im/app/#/room/#fedora:matrix.org",
            parentId: "bu8fdOZAucTS",
          },
        ],
      },
      {
        id: "FXvJNZacAVec",
        title: "Red Hat",
        index: 5,
        dateAdded: 1176674113000,
        type: "folder",
        parentId: "toolbar_____",
        dateGroupModified: 1677328173716,
        children: [
          {
            id: "jt08qpATl5Ay",
            title: "Red Hat",
            index: 0,
            dateAdded: 1176674148000,
            type: "bookmark",
            url: "https://www.redhat.com/",
            parentId: "FXvJNZacAVec",
          },
          {
            id: "bo_5VPZszX0g",
            title: "JBoss Developer Community",
            index: 1,
            dateAdded: 1176674189000,
            type: "bookmark",
            url: "https://developer.jboss.org/welcome",
            parentId: "FXvJNZacAVec",
          },
          {
            id: "-HH7Uj4ohMoi",
            title: "OpenShift Origin",
            index: 2,
            dateAdded: 1503757022000,
            type: "bookmark",
            url: "https://www.openshift.org/",
            parentId: "FXvJNZacAVec",
          },
          {
            id: "qAfXPvpc1yJ2",
            title: "OpenSource.com",
            index: 3,
            dateAdded: 1677328173716,
            type: "bookmark",
            url: "https://opensource.com/",
            parentId: "FXvJNZacAVec",
          },
          {
            id: "xHM6CZvJKiCe",
            title: "The Open Source Way",
            index: 4,
            dateAdded: 1269287471000,
            type: "bookmark",
            url: "https://www.theopensourceway.org/",
            parentId: "FXvJNZacAVec",
          },
        ],
      },
      {
        id: "rQF1zqf1BmRN",
        title: "Free Content",
        index: 6,
        dateAdded: 1176674388000,
        type: "folder",
        parentId: "toolbar_____",
        dateGroupModified: 1677328173716,
        children: [
          {
            id: "7YWt1NCmCR_a",
            title: "Wikipedia",
            index: 0,
            dateAdded: 1176674401000,
            type: "bookmark",
            url: "https://www.wikipedia.org/",
            parentId: "rQF1zqf1BmRN",
          },
          {
            id: "1CId4QXbLAS4",
            title: "LibriVox",
            index: 1,
            dateAdded: 1241209006000,
            type: "bookmark",
            url: "https://librivox.org/",
            parentId: "rQF1zqf1BmRN",
          },
          {
            id: "UQeqP11W1tZi",
            title: "Open Clip Art",
            index: 2,
            dateAdded: 1269287471000,
            type: "bookmark",
            url: "https://openclipart.org/",
            parentId: "rQF1zqf1BmRN",
          },
          {
            id: "4d78BSx2b6ai",
            title: "Free Sound",
            index: 3,
            dateAdded: 1677328173716,
            type: "bookmark",
            url: "https://www.freesound.org/",
            parentId: "rQF1zqf1BmRN",
          },
          {
            id: "mKjXhSZ4UmMj",
            title: "Creative Commons",
            index: 4,
            dateAdded: 1176674776000,
            type: "bookmark",
            url: "https://creativecommons.org/",
            parentId: "rQF1zqf1BmRN",
          },
          {
            id: "QadkcyGr9BzC",
            title: "Pixabay",
            index: 5,
            dateAdded: 1499702460000,
            type: "bookmark",
            url: "https://pixabay.com/",
            parentId: "rQF1zqf1BmRN",
          },
        ],
      },
    ],
  },
  {
    id: "unfiled_____",
    title: "Other Bookmarks",
    index: 2,
    dateAdded: 1677328173656,
    type: "folder",
    parentId: "root________",
    dateGroupModified: 1677328173703,
    children: [],
  },
  {
    id: "mobile______",
    title: "Mobile Bookmarks",
    index: 3,
    dateAdded: 1677328173658,
    type: "folder",
    parentId: "root________",
    dateGroupModified: 1677328173703,
    children: [],
  },
];

export const bookmarks = new SyncBookmarksAdapter(
  new BookmarksApi(bookmarksInitialState),
);
